id: P81B01155
initial_creation_type: input
source_metadata:
  title: Prajñāpāramitāpiṇḍārtha
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: members of the Digital Sanskrit Buddhist Canon Input Project
  contribution to GRETIL: members of the Digital Sanskrit Buddhist Canon Input Project
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:13:19.723717'
last_modified_at: '2022-03-09T15:13:19.723734'
